# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 386)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 50, 31, 31))
        self.pushButton.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(81, 0, 0, 255), stop:1 rgba(255, 123, 123, 158));\n"
"background-color: rgb(162, 162, 162);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 50, 31, 31))
        self.pushButton_2.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(81, 0, 0, 255), stop:1 rgba(255, 123, 123, 158));\n"
"background-color: rgb(162, 162, 162);\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 50, 31, 31))
        self.pushButton_3.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(81, 0, 0, 255), stop:1 rgba(255, 123, 123, 158));\n"
"background-color: rgb(162, 162, 162);\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 50, 441, 251))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 10, 221, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(420, 10, 56, 17))
        self.pushButton_4.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(81, 0, 0, 255), stop:1 rgba(255, 123, 123, 158));\n"
"background-color: rgb(162, 162, 162);\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 90, 71, 31))
        self.pushButton_5.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(81, 0, 0, 255), stop:1 rgba(255, 123, 123, 158));\n"
"background-color: rgb(162, 162, 162);\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 10, 56, 17))
        self.pushButton_6.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(81, 0, 0, 255), stop:1 rgba(255, 123, 123, 158));\n"
"background-color: rgb(162, 162, 162);\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(340, 330, 241, 21))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 330, 91, 20))
        self.label_2.setObjectName("label_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(200, 330, 51, 20))
        self.checkBox.setObjectName("checkBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(34, 269, 81, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 300, 91, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 310, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 320, 91, 16))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "СХЕМ"))
        self.pushButton_2.setText(_translate("MainWindow", "СПУТ"))
        self.pushButton_3.setText(_translate("MainWindow", "ГИБР"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "Найти!"))
        self.pushButton_5.setText(_translate("MainWindow", "СОХРАНИТЬ"))
        self.pushButton_6.setText(_translate("MainWindow", "СБРОСИТЬ"))
        self.label_2.setText(_translate("MainWindow", "Вывод полного адресса:"))
        self.checkBox.setText(_translate("MainWindow", "Индекс"))
        self.label_3.setText(_translate("MainWindow", "CREATED BY:"))
        self.label_4.setText(_translate("MainWindow", "МЕЛЕХИН МАТВЕЙ"))
        self.label_5.setText(_translate("MainWindow", "МОШЕНКО АРТЁМ"))
        self.label_6.setText(_translate("MainWindow", "МАРКИН АЛЕКСАНДР"))
